#pragma once

#define TILE_DEFAULT_LIGHT_LEVEL 50
#define TILE_DEFAULT_MAX_LIGHT_LEVEL 100
#define TILE_DEFAULT_MIN_LIGHT_LEVEL 0
#define TILE_DEFAULT_LIGHT_INCR (1.0f / TILE_DEFAULT_MAX_LIGHT_LEVEL)
